Vagrant.configure("2") do |config|

  # Definindo a imagem base da VM como "centos/7"
  config.vm.box = "centos/7"

  # Verificando se o plugin "vagrant-vbguest" está instalado e desabilitando atualizações automáticas
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  # Configurando o nome do host da VM como "control-node"
  config.vm.hostname = "db01"

  # Configurando uma rede privada com um endereço IP estático
  config.vm.network "private_network", ip: "192.168.56.4"

  config.vm.network "forwarded_port", guest: 3306, host:3306

  # Provisão da VM com um script shell localizado em "provision.sh"
  config.vm.provision "shell", path: "provision.sh"
end
